### ISSUE TITLE
能否提供新的构建版本

### ISSUE THREAD

**Issue by chengwu26** [xxnuo/vaultwarden-windows#1]
我尝试自己在windows平台构建最新版本, 出现main.rs中第48行的unix信号的报错, 我不会使用rust, 这一步让我无法继续构建

您是否有计划提供新的版本, 或者教我如何修改代码让其顺利构建

**Comment by xxnuo** [comment]
我试试，写个提取脚本就行

**Comment by xxnuo** [comment]
@OVector 我研究了一下 vaultwarden 新版服务端代码，已经不兼容 Windows 编译了，修改代码改动比较大。如果你很想在Windows下用，建议你用 wsl 运行 vaultwarden 吧

**Comment by chengwu26** [comment]
好的, 谢谢, 辛苦您了
